# Generated by Django 2.2.3 on 2019-09-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0002_auto_20190903_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Grid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('connections', models.ManyToManyField(related_name='_system_connections_+', to='grid.System')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Sector')),
            ],
        ),
    ]
