- _type: Tag
  name: Gas Giant

- _type: Inspiration
  name: Gas Giant
  description: "Though the Imperium primarily desires worlds that humans
                can survive on (or, failing that, walk on), the presence of a
                gas giant on the reports from a long range scan has excited
                the interest of many of a Rogue Trader with the thought of
                the moons that might be concealed by its bulk. While there
                is no guarantee that a gas giant has lesser worlds in its orbit,
                much less that they are of any value, there have been enough
                fortunes made by a tightly-packed cluster of useful moons
                to give these massive orbs a reputation for good luck. This
                association has been helped in no small part by the legendary
                craft constructed at the Jovian shipyards, and the many STC
                standard ship components that bear their name.

                Gas Giants are generated with the aid of the Planet
                Creation (see page 19)."
  tags:
    - _type: Tag
      _exists: true
      name: System Element
