- _type: Config_Region
  name: The Imperium
  types:
    - _type: Weighted_Type
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          base: 1
          dice_count: 0
      value:
        _type: Config_Name
        _exists: true
        name: System
  tags:
    - _type: Tag
      _exists: true
      name: Default
- _type: Config_Region
  name: The Warp
  types:
    - _type: Weighted_Type
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          base: 1
          dice_count: 0
      value:
        _type: Config_Name
        _exists: true
        name: System
  tags:
    - _type: Tag
      _exists: true
      name: Default
- _type: Config_Region
  name: Tyranid Space
  types:
    - _type: Weighted_Type
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          base: 1
          dice_count: 0
      value:
        _type: Config_Name
        _exists: true
        name: System
  tags:
    - _type: Tag
      _exists: true
      name: Default
