- _type: Config_Region
  name: The Imperium
  type:
    _type: Config_Name
    _exists: true
    name: System
  tags:
    - _type: Tag
      _exists: true
      name: Default
- _type: Config_Region
  name: The Warp
  type:
    _type: Config_Name
    _exists: true
    name: System
  tags:
    - _type: Tag
      _exists: true
      name: Default
- _type: Config_Region
  name: Tyranid Space
  type:
    _type: Config_Name
    _exists: true
    name: System
  tags:
    - _type: Tag
      _exists: true
      name: Default
