- _type: Config_Route
  name: Default
  stability_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 3
      value:
        _type: Inspiration
        name: Stable Route
        description: "Gain +10 bonus on any Tests to chart this route."
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 2
      value:
        _type: Inspiration
        name: Indirect Path
        description: "Increase the duration."
        perterbations:
          - _type: Perterbation
            _exists: true
            name: Increase Days by 100%
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Haunted Passage
        description: "Increase the duration and add +10 to any rolls made for Warp Travel Hallucinations."
        perterbations:
          - _type: Perterbation
            _exists: true
            name: Increase Days by 100%
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Surly Route
        description: "Increase the duration and suffer a –10 penalty on any Psyniscience Test to Divine the Auguries."
        perterbations:
          - _type: Perterbation
            _exists: true
            name: Increase Days by 100%
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Untraceable Trail
        description: "Increase the duration and the route cannot be charted."
        perterbations:
          - _type: Perterbation
            _exists: true
            name: Increase Days by 100%
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Lightless Path
        description: "Increase the duration and the Astronomican is obscured for the trip."
        perterbations:
          - _type: Perterbation
            _exists: true
            name: Increase Days by 100%
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Byzantine Route
        description: "Increase the duration twice."
        perterbations:
          - _type: Perterbation
            _exists: true
            name: Increase Days by 200%
  days_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 2
      value:
        _type: Inspiration
        name: (1)
        description: "{days} days"
        roll_groups:
          - _type: Inspiration_Nested
            name: days
            count:
              - _type: Roll
                _exists: true
                base: 0
                dice_count: 1
                dice_size: 5
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 2
      value:
        _type: Inspiration
        name: (2)
        description: "{days} days"
        roll_groups:
          - _type: Inspiration_Nested
            name: days
            count:
              - _type: Roll
                _exists: true
                base: 5
                dice_count: 1
                dice_size: 5
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 2
      value:
        _type: Inspiration
        name: (3)
        description: "{days} days"
        roll_groups:
          - _type: Inspiration_Nested
            name: days
            count:
              - _type: Roll
                _exists: true
                base: 10
                dice_count: 2
                dice_size: 10
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 2
      value:
        _type: Inspiration
        name: (4)
        description: "{days} days"
        roll_groups:
          - _type: Inspiration_Nested
            name: days
            count:
              - _type: Roll
                _exists: true
                base: 50
                dice_count: 3
                dice_size: 10
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: (5)
        description: "{days} days"
        roll_groups:
          - _type: Inspiration_Nested
            name: days
            count:
              - _type: Roll
                _exists: true
                base: 150
                dice_count: 4
                dice_size: 10
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: (6)
        description: "{days} days"
        roll_groups:
          - _type: Inspiration_Nested
            name: days
            count:
              - _type: Roll
                _exists: true
                base: 250
                dice_count: 5
                dice_size: 10
- _type: Perterbation
  name: Increase Days by 100%
  route:
    _type: Config_Route
    name: Increase Days by 100%
    days_inspirations:
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (1)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 0
                  dice_count: 1
                  dice_size: 5
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (2)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 5
                  dice_count: 1
                  dice_size: 5
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (3)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 10
                  dice_count: 2
                  dice_size: 10
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (4)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 50
                  dice_count: 3
                  dice_size: 10
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (5)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 150
                  dice_count: 4
                  dice_size: 10
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (6)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 250
                  dice_count: 5
                  dice_size: 10
- _type: Perterbation
  name: Increase Days by 200%
  route:
    _type: Config_Route
    name: Increase Days by 200%
    days_inspirations:
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (1)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 0
                  dice_count: 1
                  dice_size: 5
                - _type: Roll
                  _exists: true
                  base: 0
                  dice_count: 1
                  dice_size: 5
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (2)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 5
                  dice_count: 1
                  dice_size: 5
                - _type: Roll
                  _exists: true
                  base: 5
                  dice_count: 1
                  dice_size: 5
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (3)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 10
                  dice_count: 2
                  dice_size: 10
                - _type: Roll
                  _exists: true
                  base: 10
                  dice_count: 2
                  dice_size: 10
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (4)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 50
                  dice_count: 3
                  dice_size: 10
                - _type: Roll
                  _exists: true
                  base: 50
                  dice_count: 3
                  dice_size: 10
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (5)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 150
                  dice_count: 4
                  dice_size: 10
                - _type: Roll
                  _exists: true
                  base: 150
                  dice_count: 4
                  dice_size: 10
      - _type: Weighted_Inspiration
        value:
          _type: Inspiration
          name: (6)
          roll_groups:
            - _type: Inspiration_Nested
              name: days
              count:
                - _type: Roll
                  _exists: true
                  base: 250
                  dice_count: 5
                  dice_size: 10
                - _type: Roll
                  _exists: true
                  base: 250
                  dice_count: 5
                  dice_size: 10
