- _type: Tag
  name: Example Config

- _type: Config_Grid
  name: Default
  height: 20
  width: 20
  connectionRange: 5
  populationRate: 0.5
  connectionRate: 0.5
  rangeRateMultiplier: 0.25
  smoothingFactor: 10

- _type: Weighted_Perterbation
  weights:
    - _type: Roll
      _exists: true
      required_flags: null
      dice_count: 0
      base: 1
  parent:
    _type: Config_Grid
    _exists: true
    name: Default
  value:
    _type: Perterbation
    _exists: true
    name: Tyranid Space

- _type: Weighted_Perterbation
  weights:
    - _type: Roll
      _exists: true
      required_flags: null
      dice_count: 0
      base: 2
  parent:
    _type: Config_Grid
    _exists: true
    name: Default
  value:
    _type: Perterbation
    _exists: true
    name: The Warp

- _type: Weighted_Perterbation
  weights:
    - _type: Roll
      _exists: true
      required_flags: null
      dice_count: 0
      base: 3
  parent:
    _type: Config_Grid
    _exists: true
    name: Default
  value:
    _type: Perterbation
    _exists: true
    name: Imperial Space
