- _type: Config_Star_Cluster
  name: Default
  inspiration_tables:
    - _type: Inspiration_Table
      _exists: true
      name: Type
      tags__name: Star Cluster
  zone_extra:
    - _type: Inspiration_Extra
      count:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      inspiration_tables:
        - _type: Inspiration_Table
          name: Solar Zone
          count:
            - _type: Roll
              _exists: true
              required_flags: null
              dice_count: 0
              base: 1
          weighted_inspirations:
            - _type: Weighted_Inspiration
              weights:
                - _type: Roll
                  _exists: true
                  required_flags: null
                  dice_count: 0
                  base: 1
              value:
                _type: Inspiration
                _exists: true
                name: Inner Cauldron
                tags__name: Zone
        - _type: Inspiration_Table
          name: Solar Zone
          count:
            - _type: Roll
              _exists: true
              required_flags: null
              dice_count: 0
              base: 1
          weighted_inspirations:
            - _type: Weighted_Inspiration
              weights:
                - _type: Roll
                  _exists: true
                  required_flags: null
                  dice_count: 0
                  base: 1
              value:
                _type: Inspiration
                _exists: true
                name: Primary Biosphere
                tags__name: Zone
        - _type: Inspiration_Table
          name: Solar Zone
          count:
            - _type: Roll
              _exists: true
              required_flags: null
              dice_count: 0
              base: 1
          weighted_inspirations:
            - _type: Weighted_Inspiration
              weights:
                - _type: Roll
                  _exists: true
                  required_flags: null
                  dice_count: 0
                  base: 1
              value:
                _type: Inspiration
                _exists: true
                name: Outer Reaches
                tags__name: Zone


- _type: Inspiration_Table
  name: Type
  tags:
    - _type: Tag
      _exists: true
      name: Star Cluster
  count:
    - _type: Roll
      _exists: true
      required_flags: null
      base: 0
      dice_count: 20
      dice_size: 10
      keep_highest: -1
  weighted_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        _exists: true
        name: Mighty
        tags__name: Star Cluster

    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 3
      value:
        _type: Inspiration
        _exists: true
        name: Vigorous
        tags__name: Star Cluster

    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 3
      value:
        _type: Inspiration
        _exists: true
        name: Luminous
        tags__name: Star Cluster

    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        _exists: true
        name: Dull
        tags__name: Star Cluster

    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        _exists: true
        name: Anomalous
        tags__name: Star Cluster

- _type: Tag
  name: Star Cluster

- _type: Inspiration
  name: Mighty
  description: "The fierce light of this star dominates its system utterly. Its
                coloration is likely to be blue or blue-white. The
                Inner Cauldron is dominant, and the Primary Biosphere is weak."
  tags:
    - _type: Tag
      _exists: true
      name: Star Cluster
  inspiration_tables:
    - _type: Inspiration_Table
      _exists: true
      name: Size
      tags__name: Star Cluster

  perterbations:
    - _type: Perterbation
      name: Default Mighty
      zone:
        _type: Config_Zone
        name: Default Mighty
        inspiration_tables:
          - _type: Inspiration_Table
            name: Type
            weighted_inspirations:
              - _type: Weighted_Inspiration
                value:
                  _type: Inspiration
                  name: Inner Cauldron
                  perterbations:
                    - _type: Perterbation
                      name: Default Dominant IC
                      zone:
                        _type: Config_Zone
                        name: Default Dominant IC
                        element_count:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            base: 2
                            dice_count: 0
                            dice_size: 0
              - _type: Weighted_Inspiration
                value:
                  _type: Inspiration
                  name: Primary Biosphere
                  perterbations:
                    - _type: Perterbation
                      name: Default Weak PB
                      zone:
                        _type: Config_Zone
                        name: Default Weak PB
                        element_count:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            base: -2
                            dice_count: 0
                            dice_size: 0


- _type: Inspiration
  name: Vigorous
  description: "A steady illumination burns forth from the heart of this star.
                Its coloration is likely to be a pure white."
  tags:
    - _type: Tag
      _exists: true
      name: Star Cluster

  inspiration_tables:
    - _type: Inspiration_Table
      _exists: true
      name: Size
      tags__name: Star Cluster

- _type: Inspiration
  name: Luminous
  description: "Though it is has been long aeons since this star has shone at its
                brightest, a constant glow nonetheless provides
                for the system. It is likely to be yellow or yellow-orange in
                colour. The Inner Cauldron is weak."
  tags:
    - _type: Tag
      _exists: true
      name: Star Cluster

  inspiration_tables:
    - _type: Inspiration_Table
      _exists: true
      name: Size
      tags__name: Star Cluster

  perterbations:
    - _type: Perterbation
      name: Default Luminous
      zone:
        _type: Config_Zone
        name: Default Luminous
        inspiration_tables:
          - _type: Inspiration_Table
            name: Type
            weighted_inspirations:
              - _type: Weighted_Inspiration
                value:
                  _type: Inspiration
                  name: Inner Cauldron
                  perterbations:
                    - _type: Perterbation
                      name: Default Weak IC
                      zone:
                        _type: Config_Zone
                        name: Default Weak IC
                        element_count:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            base: -2
                            dice_count: 0
                            dice_size: 0

- _type: Inspiration
  name: Dull
  description: "The end of the star’s life advances inexorably, although it can
                still burn for millennia yet. Many stars of this type are of a
                vast size, seemingly incongruous with their wan light. Its
                coloration is likely a sullen red. The Outer Reaches are Dominant."
  tags:
    - _type: Tag
      _exists: true
      name: Star Cluster

  inspiration_tables:
    - _type: Inspiration_Table
      _exists: true
      name: Size
      tags__name: Star Cluster

  perterbations:
    - _type: Perterbation
      name: Default Dull
      zone:
        _type: Config_Zone
        name: Default Dull
        inspiration_tables:
          - _type: Inspiration_Table
            name: Type
            weighted_inspirations:
              - _type: Weighted_Inspiration
                value:
                  _type: Inspiration
                  name: Outer Reaches
                  perterbations:
                    - _type: Perterbation
                      name: Default Dominant OR
                      zone:
                        _type: Config_Zone
                        name: Default Dominant OR
                        element_count:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            base: 2
                            dice_count: 0
                            dice_size: 0

- _type: Inspiration
  name: Anomalous
  description: "The star is an unnatural outlier, shedding a strange light that
                behaves in ways it should not. Its light can be of any colour,
                even one that is not typical for a star, from bilious green to
                barely-visible purple. The Game Master can choose to make one
                Solar Zone dominant or weak at his discretion."

  tags:
    - _type: Tag
      _exists: true
      name: Star Cluster

  inspiration_tables:
    - _type: Inspiration_Table
      _exists: true
      name: Size
      tags__name: Star Cluster

  perterbations:
    - _type: Perterbation
      name: Default Anomalous
      zone:
        _type: Config_Zone
        name: Default Anomalous
        element_count:
          - _type: Roll
            _exists: true
            required_flags: null
            base: -3
            dice_count: 1
            dice_size: 5

- _type: Inspiration_Table
  name: Size
  tags:
    - _type: Tag
      _exists: true
      name: Star Cluster
  count:
    - _type: Roll
      _exists: true
      required_flags: null
      base: 1
      dice_count: 0
  weighted_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Dwarf
        description: "A smaller variant of the star that has retained less mass in
                      its orbit."
        tags:
          - _type: Tag
            _exists: true
            name: Star Cluster
        perterbations:
          - _type: Perterbation
            name: Default Dwarf
            zone:
              _type: Config_Zone
              name: Default Dwarf
              element_count:
                - _type: Roll
                  _exists: true
                  required_flags: null
                  base: -1
                  dice_count: 0

    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Moderate
        description: "A shining example of this star class."
        tags:
          - _type: Tag
            _exists: true
            name: Star Cluster

    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Giant
        description: "A larger variant of the star that has gathered an immense
                      amount of material in orbit."
        tags:
          - _type: Tag
            _exists: true
            name: Star Cluster

        perterbations:
          - _type: Perterbation
            name: Default Giant
            zone:
              _type: Config_Zone
              name: Default Giant
              element_count:
                - _type: Roll
                  _exists: true
                  required_flags: null
                  base: 1
                  dice_count: 0
