- _type: Config_Name
  name: Starship Graveyard

- _type: Tag
  name: Starship Graveyard

- _type: Config_Asset
  name: Default Starship Graveyard
  type:
    _type: Config_Name
    _exists: true
    name: Starship Graveyard
  inspiration_tables:
    - _type: Weighted_Table
      order:
        - _type: Roll
          _exists: true
          required_flags: null
          rejected_flags: null
          base: 1
          dice_count: 0
      value:
        _type: Inspiration_Table
        _exists: true
        name: Description
        tags__name: Starship Graveyard
    - _type: Weighted_Table
      order:
        - _type: Roll
          _exists: true
          required_flags: null
          rejected_flags: null
          base: 2
          dice_count: 0
      value:
        _type: Inspiration_Table
        _exists: true
        name: Origins
        tags__name: Starship Graveyard
  child_configs:
    - _type: Config_Group
      _exists: true
      name: Vessels
      tags__name: Starship Graveyard

- _type: Inspiration_Table
  name: Description
  count:
    - _type: Roll
      _exists: true
      required_flags: null
      base: 1
      dice_count: 0
  weighted_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          base: 1
          dice_count: 0
      value:
        _type: Inspiration
        name: Starship Graveyard
        description: "The remains of old naval engagements and lost expeditions
                      can be found drifting through the systems that the longago
                      admirals and explorers once in charge of these ruined
                      flotillas had sought to claim. The remains of an invasion
                      fleet pounded to scrap by the system’s defenders could circle
                      the system’s rim, or a collection of scout ships might hover
                      just beyond the orbit of a planet where they could have
                      replenished their failing supplies. More often, determining
                      the origin of the vessels involved is impossible, after centuries
                      of degradation and the attention of passing scavengers have
                      long since stripped away anything recognisable from their
                      hulls. Still, taking time to search the wreckage of a Starship
                      Graveyard proves profitable as often as not. Supplies such
                      as fuel, spare plating, or conduits can be found intact with
                      some frequency, and some hulks contain full cargo holds, or
                      even intact Ship Components of great worth.

                      A Starship Graveyard can consist of anywhere from three
                      to twenty or more vessels, although most of them are far
                      beyond any attempts at salvage. The origin of these ships
                      is only rarely consistent with any star-faring inhabitation
                      a System might have. A successful defence would allow
                      them full salvage of any losses, and an intact civilisation
                      usually means there have been no unsuccessful defences. To
                      determine the make-up of the fleet (or fleets) involved, roll
                      on Table 1–5: Starship Graveyard Origins.

                      The nature of the race or races that produced the ships
                      is left to the GM’s discretion. Game Masters can use
                      the ships from pages 194–196 of ROGUE TRADER Core
                      Rulebook, which usually indicates a fleet of human (but
                      not necessarily Imperial) construction, or, if they have
                      access to volumes such as BATTLEFLEET KORONUS, they
                      can find sundry strange and deadly xenos ships there. A
                      Starship Graveyard contains 1d10+2 Archeotech Cache or
                      Xenos Ruins Resources, each of which has an Abundance
                      of 25+2d10 (see page 27). There might even be a mix
                      of Archeotech Cache and Xenos Ruins Resources, if this
                      stellar grave site is an ancient battlefield where multiple
                      species met in cataclysmic conflict.

                      Any individual vessel or conglomeration of ships can be
                      treated as a Derelict Vessel Encounter Site (see pages 59–60),
                      should the Explorers choose to board it."

  tags:
    - _type: Tag
      _exists: true
      name: Starship Graveyard


- _type: Inspiration_Table
  name: Origins
  count:
    - _type: Roll
      _exists: true
      required_flags: null
      base: 1
      dice_count: 0
  weighted_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 15
      value:
        _type: Inspiration
        name: Crushed Defence Force/Routed Invasion
        description: "The wreckage is all that remains of a defeated
                      battlefleet. Whichever side of the long-ago conflflict
                      that fifielded these vessels was decisively defeated, with
                      most or all of the hulks belonging to the same force. The
                      graveyard consists of {ships} ships, of which most or all have
                      been shattered beyond any value."
        inspiration_tables:
          - _type: Weighted_Table
            value:
              _type: Inspiration_Table
              _exists: true
              name: First Fleet
        roll_groups:
          - _type: Inspiration_Table
            name: ships
            count:
              - _type: Roll
                _exists: true
                required_flags: null
                base: 0
                dice_count: 2
                dice_size: 5
                keep_highest: 0
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          rejected_flags: null
          dice_count: 0
          base: 5
      value:
        _type: Inspiration
        name: Fleet Engagement
        description: "A massive conflflict once raged here, as evidenced by the
                      abundance of battle-scarred hulls left behind by both
                      sides. The graveyard consists of 1d10+6 hulks, and can
                      also include vast fifields of unexploded mines, spent
                      volleys of torpedoes, or the drifting wings of attack
                      craft. Roughly half of the ships and materiel expended
                      came from each side. The fury of the conflflict consumed
                      much of value, but the sturdy construction of warships
                      means that at least a few of them might be worth
                      salvaging."
        inspiration_tables:
          - _type: Weighted_Table
            value:
              _type: Inspiration_Table
              _exists: true
              name: First Fleet
          - _type: Weighted_Table
            value:
              _type: Inspiration_Table
              _exists: true
              name: Second Fleet
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 15
      value:
        _type: Inspiration
        name: Lost Explorers
        description: "These ships were not lost to enemy action, but to
                      overextended supply vaults, or the failure of long
                      suffering vital systems. The expedition is unlikely to
                      include as many as even half a dozen ships, but few (if
                      any) of them have deteriorated enough to prohibit salvage
                      efforts."
        inspiration_tables:
          - _type: Weighted_Table
            value:
              _type: Inspiration_Table
              _exists: true
              name: First Fleet
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 30
      value:
        _type: Inspiration
        name: Plundered Convoy
        description: "A lost shipping lane of some kind might have once crossed
                      this system, as evidenced by this gutted procession of
                      transports and cargo vessels. Their holds have been long
                      since emptied, but it is possible their attackers might
                      have missed something of value. There are {ships} ships in
                      the convoy, of which most or all remain intact enough to
                      allow boarding, but little else."
        inspiration_tables:
          - _type: Weighted_Table
            value:
              _type: Inspiration_Table
              _exists: true
              name: First Fleet
        roll_groups:
          - _type: Inspiration_Table
            name: ships
            count:
              - _type: Roll
                _exists: true
                required_flags: null
                base: 2
                dice_count: 1
                dice_size: 5
                keep_highest: 0
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 25
      value:
        _type: Inspiration
        name: Skirmish
        description: "Elements from two different battleflfleets clashed here,
                      with each leaving behind a handful of their complement.
                      The graveyard consists of {ships} hulks. Roughly half of the
                      ships came from each side. The fury of the conflflict all
                      ships involved, but the sturdy construction of warships
                      means that at least a few of them might be worth
                      salvaging."
        inspiration_tables:
          - _type: Weighted_Table
            value:
              _type: Inspiration_Table
              _exists: true
              name: First Fleet
          - _type: Weighted_Table
            value:
              _type: Inspiration_Table
              _exists: true
              name: Second Fleet
        roll_groups:
          - _type: Inspiration_Table
            name: ships
            count:
              - _type: Roll
                _exists: true
                required_flags: null
                rejected_flags: null
                base: 3
                dice_count: 1
                dice_size: 5
                keep_highest: 0
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 10
      value:
        _type: Inspiration
        name: Unknown Provenance
        description: "The bizarre assortment of different vessels drifting past
                      defies easy explanation. It is likely to bring to mind the
                      eerie legends of the Processional of the Damned, where
                      broken ships from across the Expanse arrive like spectres
                      in some strange afterlife. Whether associated with that
                      haunted realm, or the result of some more mundane
                      confusion, the graveyard consists of the twisted wreckage
                      of dozens of utterly ruined ships of all kinds, as well as
                      {ships} hulks in varying degrees of integrity. None of the
                      hulks share an origin."
        perterbations:
          - _type: Perterbation
            flags: starship_graveyard_xenos,starship_graveyard_archeotech
        roll_groups:
          - _type: Inspiration_Table
            name: ships
            count:
              - _type: Roll
                _exists: true
                required_flags: null
                base: 0
                dice_count: 1
                dice_size: 5
                keep_highest: 0
  tags:
    - _type: Tag
      _exists: true
      name: Starship Graveyard

- _type: Config_Group
  name: Vessels
  tags:
    - _type: Tag
      _exists: true
      name: Starship Graveyard
  types:
    - _type: Weighted_Type
      weights:
        - _type: Roll
          required_flags: starship_graveyard_archeotech
          base: 1
          dice_count: 0
      value:
        _type: Config_Name
        _exists: true
        name: Archeotech Cache
    - _type: Weighted_Type
      weights:
        - _type: Roll
          required_flags: starship_graveyard_xenos
          base: 10
          dice_count: 0
      value:
        _type: Config_Name
        _exists: true
        name: Xenos Ruins
  count:
    - _type: Roll
      _exists: true
      required_flags: null
      dice_count: 1
      dice_size: 10
      base: 2

- _type: Inspiration_Table
  name: First Fleet
  count:
    - _type: Roll
      _exists: true
      required_flags: null
      dice_count: 0
      base: 1
  weighted_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Ancient Human Fleet
        perterbations:
          - _type: Perterbation
            flags: starship_graveyard_archeotech
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 4
      value:
        _type: Inspiration
        name: Unknown Xenos Fleet
        perterbations:
          - _type: Perterbation
            flags: starship_graveyard_xenos,xenos_ruins_unknown
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          rejected_flags: null
          dice_count: 0
          base: 2
      value:
        _type: Inspiration
        name: Eldar Fleet
        perterbations:
          - _type: Perterbation
            flags: starship_graveyard_xenos,xenos_ruins_eldar
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 4
      value:
        _type: Inspiration
        name: Egarian Fleet
        perterbations:
          - _type: Perterbation
            flags: starship_graveyard_xenos,xenos_ruins_egarian
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Yu'Vath Fleet
        perterbations:
          - _type: Perterbation
            flags: starship_graveyard_xenos,xenos_ruins_yuvath
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Ork Fleet
        perterbations:
          - _type: Perterbation
            flags: starship_graveyard_xenos,xenos_ruins_ork
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        name: Kroot Fleet
        perterbations:
          - _type: Perterbation
            flags: starship_graveyard_xenos,xenos_ruins_kroot


- _type: Inspiration_Table
  name: Second Fleet
  count:
    - _type: Roll
      _exists: true
      required_flags: null
      dice_count: 0
      base: 1
  weighted_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        _exists: true
        name: Ancient Human Fleet
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 4
      value:
        _type: Inspiration
        _exists: true
        name: Unknown Xenos Fleet
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          rejected_flags: null
          dice_count: 0
          base: 2
      value:
        _type: Inspiration
        _exists: true
        name: Eldar Fleet
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 4
      value:
        _type: Inspiration
        _exists: true
        name: Egarian Fleet
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        _exists: true
        name: Yu'Vath Fleet
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        _exists: true
        name: Ork Fleet
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          dice_count: 0
          base: 1
      value:
        _type: Inspiration
        _exists: true
        name: Kroot Fleet
