- _type: Config_Zone
  name: Default
  element_count:
    - _type: Roll
      _exists: true
      required_flags: null
      base: 0
      dice_count: 1
      dice_size: 5

- _type: Tag
  name: Zone

- _type: Inspiration
  name: Inner Cauldron
  tags:
    - _type: Tag
      _exists: true
      name: Zone
  perterbations:
    - _type: Perterbation
      name: Default IC
      flags: zone_inner_cauldron
      zone:
        _type: Config_Zone
        name: Default IC
        order:
          - _type: Roll
            _exists: true
            required_flags: null
            base: 1
            dice_count: 0
            dice_size: 0
      element:
        _type: Config_Element
        _exists: true
        name: Default IC

- _type: Inspiration
  name: Primary Biosphere
  tags:
    - _type: Tag
      _exists: true
      name: Zone
  perterbations:
    - _type: Perterbation
      name: Default PB
      flags: zone_primary_biosphere
      zone:
        _type: Config_Zone
        name: Default PB
        order:
          - _type: Roll
            _exists: true
            required_flags: null
            base: 2
            dice_count: 0
            dice_size: 0
      element:
        _type: Config_Element
        _exists: true
        name: Default PB

- _type: Inspiration
  name: Outer Reaches
  tags:
    - _type: Tag
      _exists: true
      name: Zone
  perterbations:
    - _type: Perterbation
      name: Default OR
      flags: zone_outer_reaches
      zone:
        _type: Config_Zone
        name: Default OR
        order:
          - _type: Roll
            _exists: true
            required_flags: null
            base: 3
            dice_count: 0
            dice_size: 0
      element:
        _type: Config_Element
        _exists: true
        name: Default OR
