- _type: Config_Name
  name: Solar Zone

- _type: Tag
  name: Solar Zone

- _type: Tag
  name: Inner Cauldron

- _type: Tag
  name: Primary Biosphere

- _type: Tag
  name: Outer Reaches

- _type: Config_Asset
  name: Default Solar Zone
  type:
    _type: Config_Name
    _exists: true
    name: Solar Zone
  child_configs:
    - _type: Config_Group
      name: Elements
      type:
        _type: Config_Name
        _exists: true
        name: Element
      count:
        - _type: Roll
          _exists: true
          required_flags: null
          base: 0
          dice_count: 1
          dice_size: 5

- _type: Inspiration_Table
  name: Type
  extra_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          base: 1
          dice_count: 0
      value:
        _type: Inspiration
        name: Inner Cauldron
        description: "The region of the solar system closet to the solar
                      center."
        perterbations:
          - _type: Perterbation
            flags: zone_inner_cauldron
            configs:
              - _type: Config_Asset
                name: Inner Cauldron
                type:
                  _type: Config_Name
                  _exists: true
                  name: Element
                inspiration_tables:
                  - _type: Inspiration_Table
                    name: Type
                    weighted_inspirations:
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 20
                        value:
                          _type: Inspiration
                          _exists: true
                          name: No Feature
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 9
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Asteroid Cluster
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 12
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Dust Cloud
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 4
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Gas Giant
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 11
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Gravity Riptide
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 20
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Planet
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 12
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Radiation Bursts
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 12
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Solar Flares
                          tags__name: System Element


  tags:
    - _type: Tag
      _exists: true
      name: Inner Cauldron

- _type: Inspiration_Table
  name: Type
  extra_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          base: 1
          dice_count: 0
      value:
        _type: Inspiration
        name: Primary Biosphere
        description: "The region of the solar system comfortably far from
                      the solar center."
        perterbations:
          - _type: Perterbation
            flags: zone_primary_biosphere
            configs:
              - _type: Config_Asset
                name: Primary Biosphere
                type:
                  _type: Config_Name
                  _exists: true
                  name: Element
                inspiration_tables:
                  - _type: Inspiration_Table
                    name: Type
                    weighted_inspirations:
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 20
                        value:
                          _type: Inspiration
                          _exists: true
                          name: No Feature
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 10
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Asteroid Belt
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 11
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Asteroid Cluster
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 6
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Derelict Station
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 11
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Dust Cloud
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 6
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Gravity Riptide
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 29
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Planet
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 7
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Starship Graveyard
                          tags__name: System Element
  tags:
    - _type: Tag
      _exists: true
      name: Primary Biosphere

- _type: Inspiration_Table
  name: Type
  extra_inspirations:
    - _type: Weighted_Inspiration
      weights:
        - _type: Roll
          _exists: true
          required_flags: null
          base: 1
          dice_count: 0
      value:
        _type: Inspiration
        name: Outer Reaches
        description: "The region of the solar system absent of any solar
                      warmth."
        perterbations:
          - _type: Perterbation
            flags: zone_outer_reaches
            configs:
              - _type: Config_Asset
                name: Outer Reaches
                type:
                  _type: Config_Name
                  _exists: true
                  name: Element
                inspiration_tables:
                  - _type: Inspiration_Table
                    name: Type
                    weighted_inspirations:
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 20
                        value:
                          _type: Inspiration
                          _exists: true
                          name: No Feature
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 9
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Asteroid Belt
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 11
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Asteroid Cluster
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 6
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Derelict Station
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 9
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Dust Cloud
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 18
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Gas Giant
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 7
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Gravity Riptide
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 13
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Planet
                          tags__name: System Element
                      - _type: Weighted_Inspiration
                        weights:
                          - _type: Roll
                            _exists: true
                            required_flags: null
                            dice_count: 0
                            base: 7
                        value:
                          _type: Inspiration
                          _exists: true
                          name: Starship Graveyard
                          tags__name: System Element
  tags:
    - _type: Tag
      _exists: true
      name: Outer Reaches
