# Generated by Django 2.2.9 on 2020-02-02 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Star_Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Config_Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
                ('height', models.PositiveSmallIntegerField(blank=True, default=20)),
                ('width', models.PositiveSmallIntegerField(blank=True, default=20)),
                ('connectionRange', models.PositiveSmallIntegerField(blank=True, default=5)),
                ('populationRate', models.FloatField(blank=True, default=0.5)),
                ('connectionRate', models.FloatField(blank=True, default=0.5)),
                ('rangeRateMultiplier', models.FloatField(blank=True, default=0.5)),
                ('smoothingFactor', models.FloatField(blank=True, default=0.5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Config_Star_Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Config_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grid_Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=39)),
            ],
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
                ('description', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Perterbation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
                ('star_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Config_Star_Cluster')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Config_System')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_count', models.PositiveSmallIntegerField()),
                ('dice_size', models.PositiveSmallIntegerField()),
                ('base', models.IntegerField()),
                ('multiplier', models.IntegerField()),
                ('keep_highest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weighted_Perterbation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Config_Grid')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Perterbation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weighted_Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
                ('star_clusters', models.ManyToManyField(to='plan.Config_Star_Cluster')),
                ('systems', models.ManyToManyField(to='plan.Config_System')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Inspiration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inspiration',
            name='perterbation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Perterbation'),
        ),
        migrations.AddField(
            model_name='inspiration',
            name='rolls',
            field=models.ManyToManyField(related_name='rolls', to='plan.Roll'),
        ),
        migrations.CreateModel(
            name='Grid_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Perterbation')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Grid_Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Grid_Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='plan.Grid_System')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='plan.Grid_System')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolls', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Inspiration')),
            ],
        ),
        migrations.AddField(
            model_name='config_system',
            name='star_cluster_count',
            field=models.ManyToManyField(related_name='star_cluster_count', to='plan.Roll'),
        ),
        migrations.AddField(
            model_name='config_system',
            name='system_feature_count',
            field=models.ManyToManyField(related_name='system_feature_count', to='plan.Roll'),
        ),
        migrations.AddField(
            model_name='config_star_cluster',
            name='star_count',
            field=models.ManyToManyField(related_name='star_count', to='plan.Roll'),
        ),
        migrations.CreateModel(
            name='Asset_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
                ('details', models.ManyToManyField(related_name='details', to='plan.Detail')),
                ('star_clusters', models.ManyToManyField(related_name='star_clusters', to='plan.Asset_Star_Cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset_star_cluster',
            name='stars',
            field=models.ManyToManyField(related_name='stars', to='plan.Detail'),
        ),
        migrations.CreateModel(
            name='Asset_Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
                ('systems', models.ManyToManyField(related_name='systems', to='plan.Asset_System')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
