# Generated by Django 2.2.6 on 2019-12-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=39)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeightedRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Region')),
            ],
        ),
        migrations.CreateModel(
            name='SectorSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Region')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='SectorRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='plan.SectorSystem')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='plan.SectorSystem')),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=25)),
                ('height', models.PositiveSmallIntegerField(blank=True, default=20)),
                ('width', models.PositiveSmallIntegerField(blank=True, default=20)),
                ('connectionRange', models.PositiveSmallIntegerField(blank=True, default=5)),
                ('populationRate', models.FloatField(blank=True, default=0.5)),
                ('connectionRate', models.FloatField(blank=True, default=0.5)),
                ('rangeRateMultiplier', models.FloatField(blank=True, default=0.5)),
                ('smoothingFactor', models.FloatField(blank=True, default=0.5)),
                ('weightedRegions', models.ManyToManyField(blank=True, to='plan.WeightedRegion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
