# Generated by Django 2.2.6 on 2019-11-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='smoothingFactor',
            field=models.FloatField(blank=True, default=0.5),
        ),
    ]
