# Generated by Django 2.2.3 on 2019-10-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190903_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='connectionRange',
            field=models.PositiveSmallIntegerField(blank=True, default=5),
        ),
    ]
